version_control = "git"  # initialize new repositories with git
version = "0.1.0"        # start new projects at version 0.1.0

[author]
name = "Nathan Musoke"
email = "nathan.musoke@gmail.com"
github_username = "musoke"
