directory: ~/media/music
library: ~/media/music/musiclibrary.blb

asciify_paths: yes

import:
    move: yes
    write: yes
    languages: en


# The default replacements, plus " " -> "-"
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '\s': '-'

plugins: >
    fromfilename
    fetchart
    mbsync

fetchart:
    store_source: yes
