directory: ~/media/music
library: ~/media/music/musiclibrary.blb

asciify_paths: yes

import:
    move: yes
    write: yes
    languages: en
    log: ~/media/music/beets-log.txt

match:
    preferred:
        countries: ['CA']
        media: ['CD']

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title

# The default replacements, plus " " -> "-"
replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '\s': '-'

plugins: >
    fromfilename
    fetchart
    mbsync
    ipfs

fetchart:
    store_source: yes

ipfs:
  auto: no
